#!/usr/bin/env bash
#display information about subdomains
#$1=domain, $2=sub
info ()
{
    RECORD_TYPE=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk '{ printf $4 }')
    DESTINATION=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk '{ printf $5 }')
    echo "The subdomain $2 is a $RECORD_TYPE record and points to $DESTINATION"
}

if [ "$#" == 2 ]
then
    info "$1" "$2"
else
    info "$1" "www"
    info "$1" "lb-01"
    info "$1" "web-01"
    info "$1" "web-02"
fi
