#!/usr/bin/env bash
#display information about subdomains
domain=$1
sub=$2
subdomains=("www" "lb-01" "web-01" "web-02")
if [ $# == 2 ];
then
    $2
else
    subdomains=("www" "lb-01" "web-01" "web-02")
fi
for sub in "${subdomains[@]}"
do
   echo -n "The subdomain $sub"
   dig "$sub.$1" | grep -A1 "ANSWER SECTION:" | tail -n 1 | awk '{ print " is a "$4 " record and points to " $5}'
done
