#!/usr/bin/env bash
#redirect to another page
new="rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx start
sudo sed -i "46i $new" /etc/nginx/sites-available/default
sudo service nginx restart
