#!/usr/bin/env bash
#Configure Nginx with your HTTP response containing a custom header
new="\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
not_found="error_page 404 /custom_404.html;\nlocation = /custom_404.html {\n\troot /usr/share/nginx/html;\n\tinternal;\n}\n"
header="\tadd_header X-Served-By: $HOSTNAME;\n"
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo sed -i "46i $new" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i "52i $not_found" /etc/nginx/sites-available/default
sudo sed -i "45i $header" /etc/nginx/sites-available/default
sudo service nginx start
