#!/usr/bin/env bash
#Configure Nginx with your HTTP response containing a custom header
header="add_header X-Served-By: $HOSTNAME;\n"
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "45i $header" /etc/nginx/sites-available/default
sudo service nginx restart
