#!/usr/bin/env bash
#Install and configure HAproxy on lb-01 server
front="\nfrontend cristinarueda.tech\n\tbind *:80\n\tmode http\n\tdefault_backend webservers\n"
back="\nbackend webservers\n\tbalance roundrobin\n\tserver 1481-web-01 35.237.14.137:80 check\n\tserver 1481-web-02 34.74.232.51:80 check\n"
sudo apt-get -y update
sudo apt-get -y install haproxy=1.8.\*
sudo sed -i "39a $front $back" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
